version: '3.4'
services:
  # database
  postgres:
    image: postgres:14-alpine
    container_name: wss-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      # Password is required
      - POSTGRES_PASSWORD=${POSTGRES_USER:-postgres}
      - DB_NAME=${POSTGRES_USER:-postgres}
    ports:
      - 5432:5432
    volumes:
      # Database data will be stored in the pg_data volume
      - ./pg_data:/var/lib/postgresql
      # The init.sh script will be executed during the first run
      - ./postgres/migrations:/docker-entrypoint-initdb.d
    restart: always

volumes:
  pg_data:
